alias av='appletviewer -J-Djava.security.policy=/home/sk/jv/registerit.policy'
alias cp='cp -r'
alias echo="echo -e"
alias ex="chmod u+x "
alias ff="firefox"
alias gc="git clone"
alias glssfshLg='tail -f ~/sw/glassfish5/glassfish/domains/domain1/logs/server.log | grep -v "^$"'
alias gp='gnuplot -persist'
alias grep='grep -n'
alias javac='javac -Xlint:unchecked -Xlint:deprecation '
alias ls='ls -m'
alias mkdir='mkdir -p'
alias myKll='sudo kill -9 '
alias pg="ping google.com"
alias ping='ping -c 3'
alias pip="pip3 "
alias prtChck='sudo netstat -lntp | grep '
alias psql='psql -d test'
alias py="python3 "
alias python='python3'
alias rnTst="java junit.textui.TestRunner "
alias R="R --quiet"
alias scpIm='scp -i ~/.ssh/skKey.pem '
alias sd='shutdown now'
alias spi='sudo pip3 install'
alias srv='python3 -m http.server'
alias sshIm='ssh -i ~/.ssh/skKey.pem -l ec2-user'
alias ssnr='sudo service network-manager restart'
alias tail="tail -f -n0"
alias trnctTmctLg='trnct $TMCT_LG $CTLN_LG'
alias trnct='truncate --size 0 '
alias unex='chmod a-x'
alias nodejs=node
alias nd=node
alias mycal='cal `date +"%m %Y"`'
alias mydt='date +"%d-%m/%a"'
alias chmod='chmod -v '
alias lclc='libreoffice --calc'
alias gcc='gcc -Wno-format-security'
